// vue-dashboard/src/views/DetailsView.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { useMeasureStore } from '../stores/measureItems'
import DimensionCard from '../components/DimensionCard.vue';
import { ref } from '@vue/reactivity';

const measureStore = useMeasureStore()
const { selectedItem } = storeToRefs(measureStore)

const modalInput = ref()
const newName = ref(selectedItem.value?.name ?? '')
const newMax = ref(selectedItem.value?.max ?? 0)

const saveValues = () => {
  if (selectedItem.value) {
    selectedItem.value.max = newMax.value;
    selectedItem.value.name = newName.value;
    modalInput.value = false
  }
}

</script>
<template>
  <div>
    <div class="hero-content" v-if="selectedItem !== undefined">
      <DimensionCard :dimension="selectedItem" @click="modalInput = true" />
    </div>
    <div class="stats shadow" v-if="selectedItem !== undefined">
      <div class="stat place-items-center" v-for="(value, index) in selectedItem.values" :key="index">
        <div class="stat-title">Value {{ index + 1 }}</div>
        <div class="stat-value">{{ value }}</div>
        <div class="stat-desc">mm</div>
      </div>
    </div>
    <div>
      <div class="modal" :class="modalInput ? 'modal-open' : ''">
        <div class="modal-box">
          <div class="form-control w-full max-w-xs">
            <label class="label">
              <span class="label-text">New dimension name</span>
            </label>
            <input type="text" v-model="newName" placeholder="Type here" class="input input-bordered w-full max-w-xs" />
            <label class="label">
              <span class="label-text">New max value</span>
            </label>
            <input type="number" v-model="newMax" placeholder="Type here" class="input input-bordered w-full max-w-xs" />
            <div class="right-align">
              <button class="btn btn-primary" @click="saveValues">Save</button>
              <button class="btn" @click="modalInput = false">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.right-align {
  display: flex;
  flex-direction: row-reverse;
  gap: 5px;
  margin-top: 10px;
}
</style>

// my-angular-dashboard/src/app/details-view/details-view.component.ts
import { Component, Input } from '@angular/core';
import { Subject } from 'rxjs';
import { MeasureItem, MeasurementItemsService } from '../measurement-items.service';

@Component({
  selector: 'app-details-view',
  templateUrl: './details-view.component.html',
  styleUrls: ['./details-view.component.css']
})
export class DetailsViewComponent {
  constructor(private measService: MeasurementItemsService){
    console.log("logging meas serv", this.measService)
    this.measService.selectedItemObs.subscribe(x => {
      console.log("observing", x?.name)
      this.selectedItem = x})
  }

  ngOnInit(){
    this.selectedItem = this.measService.selectedItem;
    this.newMax = this.selectedItem?.max ?? 0;
    this.newName = this.selectedItem?.name ?? "";
  }
  
  selectedItem: MeasureItem | undefined

  newMax: number = 0
  newName: string = "";
  modalInput = false;

  saveValues = () => {
    if (this.measService.selectedItem) {
      this.measService.selectedItem.max = this.newMax;
      this.measService.selectedItem.name = this.newName;      
      this.modalInput = false
      console.log("saved", this.selectedItem?.name, this.measService.selectedItem)
    }
  }
  showModal() {
    this.modalInput = true;
  }
  hideModal() {
    this.modalInput = false;
  }
}

<div>
    <div class="hero-content" *ngIf="selectedItem !== undefined">
        <app-dimension-card [dimension]="selectedItem" (click)="showModal()" />
    </div>
    <div class="stats shadow" *ngIf="selectedItem !== undefined">
        <div class="stat place-items-center" *ngFor="let value of selectedItem?.values; index as i">
            <div class="stat-title">Value {{ i + 1 }}</div>
            <div class="stat-value">{{ value }}</div>
            <div class="stat-desc">mm</div>
        </div>
    </div>
    <div>
        <div class="modal" [ngClass]="modalInput ? 'modal-open' : ''">
            <div class="modal-box">
                <div class="form-control w-full max-w-xs">
                    <label class="label">
                        <span class="label-text">New dimension name</span>
                    </label>
                    <input [(ngModel)]="newName" type="text" placeholder="Type here"
                        class="input input-bordered w-full max-w-xs" />
                    <label class="label">
                        <span class="label-text">New max value</span>
                    </label>
                    <input [(ngModel)]="newMax" type="number" placeholder="Type here"
                        class="input input-bordered w-full max-w-xs" />
                    <div class="right-align">
                        <button class="btn btn-primary" (click)="saveValues()">Save</button>
                        <button class="btn" (click)="hideModal()">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
